import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavrBar from "@/components/NavBar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mohamed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <NavrBar></NavrBar>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
